name: Deploy Cost Optimizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - name: Terraform Init & Plan
      run: |
        terraform init
        terraform plan -no-color

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve

    - name: Update Lambda Code
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd lambda_src
        zip -r ../handler.zip .
        aws lambda update-function-code --function-name aws-cost-optimizer --zip-file fileb://../handler.zip
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}